"""Add hedge_fund_analyses table

Revision ID: 19dfa3cccd5d
Revises: b789c135416b
Create Date: 2026-02-21 13:31:01.464865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dfa3cccd5d'
down_revision = 'b789c135416b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hedge_fund_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('analyst_signals_json', sa.JSON(), nullable=True),
    sa.Column('consensus_signal', sa.String(length=16), nullable=True),
    sa.Column('consensus_confidence', sa.Float(), nullable=True),
    sa.Column('analysts_used', sa.JSON(), nullable=True),
    sa.Column('decision_json', sa.JSON(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['daily_briefs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', name='uq_hf_analysis_date_ticker')
    )
    with op.batch_alter_table('hedge_fund_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_hf_analysis_date_ticker', ['date', 'ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hedge_fund_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_hf_analysis_date_ticker')

    op.drop_table('hedge_fund_analyses')
    # ### end Alembic commands ###
