"""Add recurrence and end_time to calendar_events

Revision ID: 22664cfed45e
Revises: ae136aaf6a29
Create Date: 2026-03-01 23:17:58.074130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22664cfed45e'
down_revision = 'ae136aaf6a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('recurrence_end')
        batch_op.drop_column('recurrence')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
