"""add multi-period market columns

Revision ID: a029633ebfff
Revises: 6f8f7af2e5a8
Create Date: 2026-02-21 21:44:23.489954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a029633ebfff'
down_revision = '6f8f7af2e5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_1m_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('change_3m_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('change_1y_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_column('change_1y_pct')
        batch_op.drop_column('change_3m_pct')
        batch_op.drop_column('change_1m_pct')

    # ### end Alembic commands ###
