"""Add social channels and posts tables

Revision ID: a4672d2fcf8a
Revises: 22664cfed45e
Create Date: 2026-03-20 09:19:24.133562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4672d2fcf8a'
down_revision = '22664cfed45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('feed_url', sa.String(length=2048), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    with op.batch_alter_table('social_channels', schema=None) as batch_op:
        batch_op.create_index('ix_social_channels_platform_active', ['platform', 'is_active'], unique=False)

    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hint', sa.Text(), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_cost_usd', sa.Float(), nullable=True),
    sa.Column('summary_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['social_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.create_index('ix_social_posts_channel_published', ['channel_id', 'published_at'], unique=False)
        batch_op.create_index('ix_social_posts_published', ['published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_social_posts_published')
        batch_op.drop_index('ix_social_posts_channel_published')

    op.drop_table('social_posts')
    with op.batch_alter_table('social_channels', schema=None) as batch_op:
        batch_op.drop_index('ix_social_channels_platform_active')

    op.drop_table('social_channels')
    # ### end Alembic commands ###
